image: hatsoftwares/mastalab-ci:latest

before_script:
  - export ANDROID_HOME=/opt/android-sdk-linux
  - export PATH=$PATH:/opt/android-sdk-linux/platform-tools/
  - chmod +x gradlew

stages:
  - build
  - test

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - app/build/outputs/
    policy: push

lintDebug:
  stage: test
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - app/build/outputs/
    policy: pull
  script:
    - ./gradlew -Pci --console=plain :app:lintFdroidDebug -PbuildDir=lint

debugTests:
  stage: test
  cache:
    key: "$CI_COMMIT_SHA"
    paths:
      - app/build/outputs/
    policy: pull
  script:
    - ./gradlew -Pci --console=plain :app:testFdroidDebugUnitTest
