image: hatsoftwares/mastalab-ci:latest

before_script:
  - export ANDROID_HOME=/opt/android-sdk-linux
  - export PATH=$PATH:/opt/android-sdk-linux/platform-tools/
  - chmod +x gradlew

stages:
  - build-and-test
  - test

assembleDebug:
  stage: build-and-test
  script:
    - ./gradlew assembleDebug

lintDebug:
  stage: build-and-test
  script:
    - ./gradlew -Pci --console=plain :app:lintFdroidDebug -PbuildDir=lint

debugTests:
  stage: build-and-test
  script:
    - ./gradlew -Pci --console=plain :app:testFdroidDebugUnitTest
